bakecake/urls.py
from django.conf import settings
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include, re_path

from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cake.urls')),
    path('api/v1/', include('cake.api_urls')),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cake/urls.py
from .views import *
from django.urls import path

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('register/', registration, name='registration'),
    path('lk/', ProfileView.as_view(), name='lk'),
    path('catalog/', CakeCatalogView.as_view(), name='catalog'),
]

cake/models.py
import requests
from django.core.validators import MinValueValidator
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.contrib.auth.validators import UnicodeUsernameValidator
from django.core.mail import send_mail
from django.db.models.signals import pre_save
from django.dispatch import receiver
from django.utils.translation import gettext_lazy as _
from django.conf import settings
from phonenumber_field.modelfields import PhoneNumberField

from .managers import ClientManager


class CakeLevel(models.Model):
    level_count = models.IntegerField(
        verbose_name='Количество уровней',
        validators=[
            MinValueValidator(1)
        ]
    )
    price = models.DecimalField(
        verbose_name='Стоимость',
        max_digits=7,
        decimal_places=2
    )

    class Meta:
        verbose_name = 'Уровень торта'
        verbose_name_plural = 'Уровни торта'

    def __str__(self):
        return f'{self.level_count}'


class CakeShape(models.Model):
    shape = models.CharField(
        max_length=50,
        verbose_name='Форма',
    )
    price = models.DecimalField(
        verbose_name='Стоимость',
        max_digits=7,
        decimal_places=2
    )

    class Meta:
        verbose_name = 'Форма торта'
        verbose_name_plural = 'Формы торта'

    def __str__(self):
        return self.shape


class CakeTopping(models.Model):
    cake_topping = models.CharField(
        max_length=50,
        verbose_name='Топпинг',
    )
    price = models.DecimalField(
        verbose_name='Стоимость',
        max_digits=7,
        decimal_places=2
    )

    class Meta:
        verbose_name = 'Топпинг'
        verbose_name_plural = 'Топпинги'

    def __str__(self):
        return self.cake_topping


class CakeBerry(models.Model):
    cake_berry = models.CharField(
        max_length=15,
        verbose_name='Ягоды',
    )
    price = models.DecimalField(
        verbose_name='Стоимость',
        max_digits=7,
        decimal_places=2
    )

    class Meta:
        verbose_name = 'Ягода'
        verbose_name_plural = 'Ягоды'

    def __str__(self):
        return self.cake_berry


class CakeDecor(models.Model):
    cake_decor = models.CharField(
        max_length=15,
        verbose_name='Декор'
    )
    price = models.DecimalField(
        verbose_name='Стоимость',
        max_digits=7,
        decimal_places=2
    )

    class Meta:
        verbose_name = 'Декор'
        verbose_name_plural = 'Декор'

    def __str__(self):
        return self.cake_decor


class Cake(models.Model):
    title = models.CharField(
        max_length=200,
        verbose_name='Название торта',
        blank=True
    )
    level = models.ForeignKey(
        CakeLevel,
        verbose_name='Количество уровней торта',
        related_name='levels',
        on_delete=models.CASCADE
    )
    shape = models.ForeignKey(
        CakeShape,
        verbose_name='Форма торта',
        related_name='shapes',
        on_delete=models.CASCADE
    )
    topping = models.ForeignKey(
        CakeTopping,
        verbose_name='Топпинг',
        related_name='toppings',
        on_delete=models.CASCADE
    )
    berry = models.ForeignKey(
        CakeBerry,
        verbose_name='Ягоды',
        related_name='berries',
        on_delete=models.CASCADE,
        blank=True,
        null=True
    )
    decor = models.ForeignKey(
        CakeDecor,
        verbose_name='Декор',
        related_name='decors',
        on_delete=models.CASCADE,
        blank=True,
        null=True
    )
    is_published = models.BooleanField(
        verbose_name='Опубликован',
        default=False
    )
    inscription = models.CharField(
        max_length=200,
        verbose_name='Надпись на торте',
        blank=True
    )
    comment = models.TextField(
        verbose_name='Комментарий',
        blank=True
    )
    image = models.ImageField(
        verbose_name='Изображение',
        blank=True,
        null=True
    )
    price = models.DecimalField(
        verbose_name='Стоимость',
        max_digits=10,
        decimal_places=2,
        blank=True,
        null=True
    )

    class Meta:
        verbose_name = 'Торт'
        verbose_name_plural = 'Торты'

    def __str__(self):
        return "{} уровень {}".format(self.title, self.level.level_count)


class Order(models.Model):
    STATUS = (
        ('new', 'Новый'),
        ('progress', 'В процессе'),
        ('delivered', 'Передан в доставку'),
        ('completed', 'Выполнен'),
        ('canceled', 'Отменен'),
    )
    STATUS_PAY = (
        ('y', 'Оплачен'),
        ('n', 'Не оплачен'),
    )

    customer = models.ForeignKey(
        'Client',
        verbose_name='Заказчик',
        related_name='orders',
        on_delete=models.CASCADE
    )
    cake = models.ForeignKey(
        Cake,
        verbose_name='Заказанный торт',
        related_name='orders',
        on_delete=models.PROTECT,
    )
    status = models.CharField(
        max_length=20,
        verbose_name='Статус заказа',
        choices=STATUS,
        default='n'
    )
    status_pay = models.CharField(
        max_length=1,
        verbose_name='Статус оплаты',
        choices=STATUS_PAY,
        default='n'
    )
    registered_at = models.DateTimeField(
        'Время регистрации заказа',
        auto_now_add=True,
        db_index=True
    )
    called_at = models.DateTimeField(
        'Время звонка клиенту',
        blank=True,
        null=True,
        db_index=True
    )
    price = models.DecimalField(
        verbose_name='Стоимость',
        max_digits=10,
        decimal_places=2
    )
    address = models.CharField(
        'Адрес доставки',
        max_length=200,
        blank=True,
    )
    delivery_date = models.DateTimeField(
        'Дата доставки',
        blank=True,
        null=True,
        db_index=True
    )
    delivered_at = models.DateTimeField(
        'Время доставки',
        blank=True,
        null=True,
        db_index=True
    )
    delivery_comments = models.TextField(
        verbose_name='Комментарий для курьера',
        blank=True
    )

    class Meta:
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'
        ordering = ['-registered_at']

    def __str__(self):
        return f'{self.customer}: {self.registered_at}'


class Pay(models.Model):
    _TYPE = (
        ('tips', "Чаевые"),
        ('service', "Услуга"),
    )
    order_id = models.BigIntegerField(verbose_name="Номер записи", blank=True, null=True)
    operation_id = models.CharField(verbose_name="ID операции", max_length=255, unique=True)
    amount = models.DecimalField(verbose_name="Сумма", max_digits=10, decimal_places=2, blank=True, null=True)
    is_success = models.BooleanField(verbose_name="Успешно", blank=True, null=True)
    _type = models.CharField(verbose_name="Тип", max_length=255, choices=_TYPE, blank=True, null=True)

    class Meta:
        verbose_name = "Платеж"
        verbose_name_plural = "Платежи"

    def __str__(self):
        return f"Платеж {self.operation_id}"


class Advertising(models.Model):
    url = models.URLField('Ссылка', blank=True)
    text = models.TextField('Текст рекламы')
    responses = models.IntegerField(
        'Количество откликов',
        null=True,
        blank=True,
        default=0,
    )

    class Meta:
        verbose_name = 'Реклама'
        verbose_name_plural = 'Реклама'


class Client(AbstractBaseUser, PermissionsMixin):
    username_validator = UnicodeUsernameValidator()

    # Имя пользователя
    name = models.CharField(
        _('name'),
        max_length=150,
        help_text=_('Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.'),
        null=True,
        blank=True
    )
    # Телефоный номер для входа
    phone_number = PhoneNumberField(
        "Телефоный номер",
        unique=True,
        help_text="Телефоный номер должен быть русского формата 8XXXXXXXXXX",
        error_messages={
            'unique': "Телефон уже зарегистрирован",
        },
    )

    # Почта
    email = models.EmailField(_("email address"), blank=True)
    # pin
    pin = models.CharField(_("pin"), max_length=4, blank=True)

    is_staff = models.BooleanField(
        _("staff status"),
        default=False,
        help_text=_("Designates whether the user can log into this admin site."),
    )
    is_active = models.BooleanField(
        _("active"),
        default=True,
        help_text=_(
            "Designates whether this user should be treated as active. "
            "Unselect this instead of deleting accounts."
        ),
    )

    objects = ClientManager()

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'phone_number'
    REQUIRED_FIELDS = ['name']

    class Meta:
        verbose_name = "Пользователь"
        verbose_name_plural = "Пользователи"

    def clean(self):
        super().clean()
        self.email = self.__class__.objects.normalize_email(self.email)

    def get_full_name(self):
        return "{} {}".format(self.name, self.phone_number)

    def get_short_name(self):
        return self.name

    def email_user(self, subject, message, from_email=None, **kwargs):
        send_mail(subject, message, from_email, [self.email], **kwargs)

    def __str__(self):
        return f"{self.name} ({self.phone_number})"



@receiver(pre_save, sender=Advertising)
def pre_save_advertising(sender, instance, **kwargs):
    if not instance.pk:
        url = "https://t.ly/api/v1/link/shorten"
        headers = {
            "Authorization": f"Bearer {settings.TLY_API_TOKEN}"
        }
        payload = {
            "long_url": "https://www.ziganshinproject.ru/"
        }
        response = requests.post(url, headers=headers, data=payload)
        response.raise_for_status()
        instance.url = response.json()["short_url"]
        instance.responses = 0

cake/forms.py
from django import forms

from .models import Client


class PhoneForm(forms.Form):
    phone_number = forms.CharField(
        max_length=15,
        widget=forms.TextInput(attrs={
            'class': 'contacts__form_iunput',
            'placeholder': '+7(999)999--99-99',
            'required': 'required'
        })
    )
    name = forms.CharField(
        max_length=50,
        widget=forms.TextInput(attrs={
            'class': 'contacts__form_iunput',
            'placeholder': 'Имя',
            'required': 'required'
        })
    )


class PinForm(forms.Form):
    pin = forms.CharField(
        max_length=4,
        widget=forms.TextInput(attrs={
            'class': 'tipsPopup__form_inputNum popup__input',
            'placeholder': '9999',
            'required': 'required',
            'style': 'width: 200px; height: 50px;'
        })
    )


class ClientEditForm(forms.ModelForm):
    class Meta:
        model = Client
        fields = ['name', 'phone_number', 'email']

cake/views.py
import json

from django.contrib.auth import login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.serializers import serialize
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, redirect
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST
from django.views.generic import TemplateView, ListView


from .forms import PhoneForm, PinForm, ClientEditForm
from .models import Cake, CakeLevel, CakeShape, CakeTopping, CakeBerry, CakeDecor, Client
from .serializers import RegistrationNumberSerializer
from .utils import get_code


class IndexView(TemplateView):
    template_name = 'cake/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Главная'
        context['levels'] = CakeLevel.objects.all().order_by('price')
        context['shapes'] = CakeShape.objects.all().order_by('price')
        context['toppings'] = CakeTopping.objects.all().order_by('price')
        context['berries'] = CakeBerry.objects.all().order_by('price')
        context['decors'] = CakeDecor.objects.all().order_by('price')
        context['cakes'] = Cake.objects.filter(is_published=True)
        return context


class CakeCatalogView(ListView):
    model = Cake
    template_name = 'cake/catalog.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['cakes'] = Cake.objects.filter(is_published=True)
        return context


class ProfileView(LoginRequiredMixin, TemplateView):
    template_name = 'cake/lk-order.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user

        client = get_object_or_404(Client, phone_number=user.phone_number)

        context['title'] = 'Личный кабинет'
        return context

    def post(self, request, *args, **kwargs):
        user = request.user
        client = get_object_or_404(Client, phone_number=user.phone_number)
        form = ClientEditForm(request.POST, instance=client)
        if form.is_valid():
            form.save()
            return redirect('lk')
        return self.get(request, *args, **kwargs)

    def dispatch(self, request, *args, **kwargs):
        if request.method.lower() == 'put':
            return self.put(request, *args, **kwargs)
        return super().dispatch(request, *args, **kwargs)

@csrf_exempt
@require_POST
def registration(request):

    if 'phone_number' in request.POST:
        cd = request.POST
        serializer = RegistrationNumberSerializer(data=request.POST)
        phone_number = cd.get('phone_number')
        if Client.objects.filter(phone_number=phone_number).exists():
            code = get_code()
            client = Client.objects.get(phone_number=phone_number)
            if (client.name != cd.get('name')):
                return JsonResponse({'status': 'error', 'errors': 'Имя не совпадает'})
            client.pin = code
            client.save()
            request.session['verification_code'] = code
            request.session['phone_number'] = phone_number
            return JsonResponse({'status': 'success', 'phone_number': phone_number, 'code': code})
        elif serializer.is_valid():
            phone_number = serializer.validated_data['phone_number']
            name = serializer.validated_data['name']
            code = get_code()
            client, created = Client.objects.get_or_create(phone_number=phone_number)
            if (not created) and (client.name != name):
                return JsonResponse({'status': 'error', 'errors': 'Имя не совпадает'})
            client.pin = code
            client.name = name
            client.save()

            request.session['verification_code'] = code
            request.session['phone_number'] = phone_number

            return JsonResponse({'status': 'success', 'phone_number': phone_number, 'code': code})
        else:
            print(serializer.errors)
            if 'phone_number' in serializer.errors:
                return JsonResponse({'status': 'error', 'errors': serializer.errors['phone_number'][0]})
            if 'name' in serializer.errors:
                return JsonResponse({'status': 'error', 'errors': serializer.errors['name'][0]})
            return JsonResponse({'status': 'error', 'errors': "Обратитесь в ТП"})
    elif 'pin' in request.POST:
        form = PinForm(request.POST)
        if form.is_valid():
            pin = form.cleaned_data['pin']
            saved_code = request.session.get('verification_code')
            phone_number = request.session.get('phone_number')
            if pin == saved_code:
                client = Client.objects.get(phone_number=phone_number)
                if (client is not None) and client.is_active:
                    login(request, client)
                    return JsonResponse({'status': 'success'})
            else:
                return JsonResponse({'status': 'error', 'message': 'Неправильный пин-код'})
        else:
            return JsonResponse({'status': 'error', 'errors': form.errors})

templates/cake/catalog.html
{% extends "base.html" %}

{% block content %}
    <main>
        <div class="container mt-header">
            <article class="row pt-header d-flex justify-content-center" id="step2">
                <h2 class="font_Gogh fs_40 cake_blue text-center mb-3">Каталог тортов</h2>
                {% for cake in cakes %}
                    <div class="col-12 col-sm-6 col-lg-4 d-flex flex-column align-items-center">
					    <div class="card border-0 cake__hover">
                            <a href="#" class="card-img-overlay"></a>
                            <img src="{{ cake.image.url}}" style="max-height: 200px; max-width: 300px;"  alt="cake" class="">
                            <span class="cake_blue mt-4 fw-lighter mb-4 text-center">{{ cake.title }}</span>
                            <span>Количество уровней: {{ cake.level }}</span>
                            <span>Форма уровней: {{ cake.shape }}</span>
                            <p>Топинг: {{ cake.topping }}</p>
                            <span>Дополнительно:</span>
                            <ul>
                                {% if cake.berry %}
                                    <li>Ягода: {{ cake.berry }}</li>
                                {% endif %}
                                {% if cake.decor %}
                                    <li>Декор: {{ cake.decor }}</li>
                                {% endif %}
                            </ul>
                            <p>Цена: {{ cake.price }}₽</p>
                        </div>
                    </div>
                {% endfor %}
                <div class="d-flex justify-content-center mt-2">
				    <a href="{% url 'index' %}"><button class="btn text-white rounded-pill shadow-none cake__button cake__bg_pink">Назад</button></a>
			    </div>

            </article>
        </div>
    </main>
{% endblock %}

templates/cake/lk-order.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<script>
        // Передаем данные клиента в глобальный объект
        window.clientData = {
            name: "{{ user.name }}",
            phone: "{{ user.phone_number }}",
            email: "{{ user.email }}"
        };
</script>
<div class="container mt-header mb-5">
	<div class="row mt-5">
		<div class="col-12 col-xxl-6 d-flex justify-content-center">
			<div><img src="{% static 'img/Cake.png' %}" alt=""></div>
		</div>
		<div class="col-12 col-xxl-6 d-flex flex-column justify-content-center align-items-center align-items-xxl-start" id="LK">
			<form class="d-none" action="{% url 'lk' %}" method="POST">
				<input v-model="Name" name="name">
				<input v-model="Phone" name="phone_number">
				<input v-model="Email" name="email">
				{% csrf_token %}
				<button type="submit" ref="HiddenFormSubmit">Apply Changes</button>
			</form>
			<v-form :validation-schema="Schema" @submit="ApplyChanges">
				<div class="d-flex w-100 justify-content-center justify-content-xxl-between align-items-center">
					<h1 class="font_Gogh fs_40 cake_blue">Личный кабинет</h1>
					<button v-if="!Edit" @click="Edit = true" class="btn shadow-none align-self-center">
						<svg xmlns="http://www.w3.org/2000/svg" width="27" height="27" fill="#DA87A9" style="border-bottom: #DA87A9 2px solid" class="bi bi-pencil-fill" viewBox="0 0 16 16">
							<path d="M12.854.146a.5.5 0 0 0-.707 0L10.5 1.793 14.207 5.5l1.647-1.646a.5.5 0 0 0 0-.708l-3-3zm.646 6.061L9.793 2.5 3.293 9H3.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.207l6.5-6.5zm-7.468 7.468A.5.5 0 0 1 6 13.5V13h-.5a.5.5 0 0 1-.5-.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.5-.5V10h-.5a.499.499 0 0 1-.175-.032l-.179.178a.5.5 0 0 0-.11.168l-2 5a.5.5 0 0 0 .65.65l5-2a.5.5 0 0 0 .168-.11l.178-.178z"/>
						</svg>
					</button>
					<button v-if="Edit" type="submit" class="btn shadow-none align-self-center">
						<svg xmlns="http://www.w3.org/2000/svg" width="27" height="27" fill="#DA87A9" style="border-bottom: #DA87A9 2px solid" class="bi bi-check-lg" viewBox="0 0 16 16">
							<path d="M12.736 3.97a.733.733 0 0 1 1.047 0c.286.289.29.756.01 1.05L7.88 12.01a.733.733 0 0 1-1.065.02L3.217 8.384a.757.757 0 0 1 0-1.06.733.733 0 0 1 1.047 0l3.052 3.093 5.4-6.425a.247.247 0 0 1 .02-.022Z"/>
						</svg>
					</button>
				</div>
				<div class="d-flex">
					<ul class="list-group">
						<li class="list-group-item border-0 ps-0">
							<span class="fs_40 cake_blue">Имя</span>
						</li>
						<li class="list-group-item border-0 ps-0">
							<h1 class="fs_40 cake_blue">Телефон</h1>
						</li>
						<li class="list-group-item border-0 ps-0">
							<h1 class="fs_40 cake_blue">Почта</h1>
						</li>
					</ul>
					<ul class="list-group">
						<li class="list-group-item border-0 py-61 position-relative">
							<v-field v-model="Name" type="text" name="name_format" id="name" :readonly="!Edit" class="form-control my-2 i cake__textinput"></v-field>
							<error-message name="name_format" class="position-absolute bottom-0 cake_pink fs_12"></error-message>
						</li>
						<li class="list-group-item border-0 py-61 position-relative">
							<v-field v-model="Phone" type="text" name="phone_format" id="phone" :readonly="!Edit" class="form-control my-2 cake__textinput"></v-field>
							<error-message name="phone_format" class="position-absolute bottom-0 cake_pink fs_12"></error-message>
						</li>
						<li class="list-group-item border-0 py-61 position-relative">
							<v-field v-model="Email" type="text" name="email_format" id="email" :readonly="!Edit" class="form-control my-2 cake__textinput"></v-field>
							<error-message name="email_format" class="position-absolute bottom-0 cake_pink fs_12"></error-message>
						</li>
					</ul>
				</div>
			</v-form>
			<h2 class="fs_40 cake_pink mt-5">Мои заказы</h2>

			{% include 'cake/my_orders.html' %}

			<a class="btn text-white rounded-pill align-self-end px-5 mt-3 shadow-none cake__button cake__bg_pink" href="{% url 'logout' %}">Выйти</a>
		</div>
	</div>
</div>
{% endblock %}

{% block js_file %}
<script src="{% static 'js/lk.js' %}"></script>
{% endblock %}

templates/cake/my_orders.html
{% if user.orders.all %}

        {% for order in user.orders.all %}
          <section class="my-2">
            <span class="cake_blue lk__order d-flex" data-bs-toggle="modal" data-bs-target="#OrderModal{{ order.id }}">
              {% if order.status == "completed" %}
                <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" class="bi bi-check-circle-fill" viewBox="0 0 16 16">
                  <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
                </svg>
              {% else %}
                <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" class="bi bi-clock-fill" viewBox="0 0 16 16">
                  <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zM8 3.5a.5.5 0 0 0-1 0V9a.5.5 0 0 0 .252.434l3.5 2a.5.5 0 0 0 .496-.868L8 8.71V3.5z"/>
                </svg>
              {% endif %}
              <span class="ms-1">#{{ order.id }} {{ order.cake }}</span>
            </span>
            <aside class="modal fade" id="OrderModal{{ order.id }}" tabindex="-1" aria-labelledby="ModalLabel2" aria-hidden="true">
              <div class="modal-dialog">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title cake_pink" id="ModalLabel{{ order.id }}">#{{ order.id }} {{ order.cake }}</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                  </div>
                  <div class="modal-body">
                    <span class="cake_blue">Уровней: {{ order.cake.level_count }}</span><br>
                    <span class="cake_blue">Форма: {{ order.cake.shape }}</span><br>
                    <span class="cake_blue">Топпинг: {{ order.cake.topping }}</span><br>
                    <span class="cake_blue">Ягоды:
                      {% if order.cake.berry %}
                        {{ order.cake.berry }}
                      {% else %}
                        —
                      {% endif %}
                    </span><br>
                    <span class="cake_blue">Декор:
                      {% if order.cake.decor %}
                        {{ order.cake.decor }}
                      {% else %}
                        —
                      {% endif %}
                    </span><br>
                    {% if order.cake.inscription %}
                      <span class="cake_blue">Надпись: ”{{ order.cake.inscription }}”</span><br>
                    {% else %}
                     <span class="cake_blue">Без надписи</span><br>
                    {% endif %}
                    <span class="cake_pink">Цена: {{ order.price }}₽</span>
                  </div>
                  <div class="modal-footer d-flex justify-content-between">
                    <span class="cake_blue d-flex align-items-center">Время доставки: {{ order.delivery_date }}</span>
                    <span class="cake_blue d-flex align-items-center">Адрес: {{ order.address }}</span>

                    <span class="cake_blue d-flex">Статус: <span class="cake_pink mx-1"> {{ order.get_status_display }}</span></span>
                    <span class="cake_blue d-flex"><span class="cake_pink mx-1"> {{ order.get_status_pay_display }}</span></span>
                  </div>
                </div>
              </div>
            </aside>
          </section>
        {% endfor %}

      {% else %}

        <span class="cake_grey">У вас еще нет заказов.</span>
        <p class="cake_grey">Вы можете добавить торт из <a href="{% url 'index' %}#step2" class="text-decoration-none cake_pink">Каталога</a> или <a href="{% url 'index' %}#step3" class="text-decoration-none cake_pink">Создать свой</a>.</p>
        <span class="cake_grey">Есть вопросы?</span>
        <span class="cake_grey">Воспользуйтесь нашим <a href="https://vk.com/devmanorg" class="text-decoration-none cake_pink">чат-ботом</a>.</span>

      {% endif %}